<?php

namespace App\Enums;

use App\Enums\Concerns\HasValues;

enum InventoryTransactionType: string
{
    use HasValues;

    case STOCK_IN = 'STOCK_IN';
    case STOCK_OUT = 'STOCK_OUT';
    case INTERNAL_BORROW_OUT = 'INTERNAL_BORROW_OUT';
    case INTERNAL_BORROW_RETURN = 'INTERNAL_BORROW_RETURN';
    case RENTAL_OUT = 'RENTAL_OUT';
    case RENTAL_RETURN = 'RENTAL_RETURN';
    case COMPENSATION_IN = 'COMPENSATION_IN';
    case ADJUSTMENT_INCREASE = 'ADJUSTMENT_INCREASE';
    case ADJUSTMENT_DECREASE = 'ADJUSTMENT_DECREASE';
    case MAINTENANCE_OUT = 'MAINTENANCE_OUT';
    case MAINTENANCE_RETURN = 'MAINTENANCE_RETURN';
    case LOST_WRITE_OFF = 'LOST_WRITE_OFF';
    case DAMAGED_WRITE_OFF = 'DAMAGED_WRITE_OFF';
}